- name: restart kubelet
  service:
    name: kubelet
    state: restarted
    enabled: true
    daemon_reload: true

- name: restart kube-proxy
  service:
    name: kube-proxy
    state: restarted
    enabled: true
    daemon_reload: true
 
