---
# 这个剧本在所有节点上运行

- name: RedHat
  block:
    - name: 关闭firewalld
      service:
        name: firewalld
        state: stopped
        enabled: false

    - name: 关闭selinux
      lineinfile:
        dest: /etc/selinux/config
        regexp: "^SELINUX="
        line: "SELINUX=disabled"

    - name: 关闭swap
      lineinfile:
        dest: /etc/fstab
        regexp: ".*swap"
        line: ""

    - name: 即时生效-selinux
      shell: setenforce 0
      ignore_errors: true
  when: ansible_os_family == "RedHat"

- name: 即时生效-swap
  shell: swapoff -a

- name: 设置时区
  timezone:
    hwclock: UTC
    name: Asia/Shanghai

- name: 添加hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].inventory_hostname }} {{ hostvars[item].node_name }}"
  with_items:
    - "{{ groups['k8s'] }}"

- name: 安装ntpdate
  package:
    name: ntpdate
    state: present

- name: 同步系统时间
  shell: ntpdate time.windows.com
  ignore_errors: true

- name: 设置时间同步定时任务
  cron:
    minute: "*/10"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "ntpdate time.windows.com"
    name: "Time synchronization with windows"
    state: present
    user: root

- name: Ubuntu系列设置DNS解析文件配置
  block:
    - name: 创建软链接覆盖原始文件
      file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: true

    - name: 重启systemd-resolved服务
      service:
        name: systemd-resolved
        enabled: true
        state: restarted
        daemon_reload: true
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version is version(18.04,">=")
