---
- include_tasks: Debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Start docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Config docker.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0644
  notify: restart docker service

- stat:
    path: /usr/bin/cri-dockerd
  register: cri

- name: 下载cri-docker二进制包
  unarchive:
    src: "{{ cri_docker_url }}"
    dest: /opt
    remote_src: true
  when: cri.stat.exists == false

- name: 创建cri-docker软链接
  file:
    src: /opt/cri-dockerd/cri-dockerd
    dest: /usr/bin/cri-dockerd
    force: true
    state: link
    mode: u+x
  when: cri.stat.exists == false

- name: 分发cri-docker service文件
  template:
    dest: /lib/systemd/system/cri-docker.service
    src: cri-docker.service.j2

- name: 启动cri-docker
  service:
    name: cri-docker
    enabled: true
    state: started
    daemon_reload: true
