---
- get_url:
    url: https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644

- package:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-ce
    - docker-compose
