---
- name: -1.给所有节点添加新节点hosts
  hosts: k8s
  tasks:
  - lineinfile:
      path: /etc/hosts
      line: "{{ hostvars[item].inventory_hostname }} {{ hostvars[item].node_name }}"
    with_items:
      - "{{ groups['k8s'] }}"

- name: 0.系统初始化
  gather_facts: true
  hosts: newnode
  roles:
    - common
  tags: common

- name: 1.部署Docker
  gather_facts: false
  hosts: newnode
  roles:
    - docker
  tags: docker

- name: 2.部署K8S Node
  gather_facts: false
  hosts: newnode
  roles:
    - node
  tags: node
