---
- name: 0.系统初始化
  hosts: all 
  roles:
    - common
  tags: common 

- name: 1.自签证书 
  hosts: localhost
  connection: local
  roles:
    - tls
  tags: tls

- name: 2.部署Docker
  hosts: k8s 
  roles:
    - docker 
  tags: docker

- name: 3.部署ETCD集群
  hosts: etcd
  roles:
    -  etcd
  tags: etcd

- name: 4.部署K8S Master
  hosts: master
  roles:
    - master
  tags: master

- name: 5.部署Nginx负载均衡并高可用
  hosts: lb
  roles:
    - ha
  tags: ha

- name: 6.部署K8S Node
  hosts: k8s 
  roles:
    - node
  tags: node

- name: 7.部署插件
  hosts: master
  roles:
    - addons
  tags: addons
